/home/recklexx/miniconda3/envs/pytorch-gpu/bin/python "/mnt/e/qiqilu/Project/2024 Foundation model/code/2_1_train_i2i.py"
/home/recklexx/miniconda3/envs/pytorch-gpu/bin/python "/mnt/e/qiqilu/Project/2024 Foundation model/code/2_1_train_i2i copy.py"
/home/recklexx/miniconda3/envs/pytorch-gpu/bin/python "/mnt/e/qiqilu/Project/2024 Foundation model/code/2_1_train_i2i copy 2.py"
/home/recklexx/miniconda3/envs/pytorch-gpu/bin/python "/mnt/e/qiqilu/Project/2024 Foundation model/code/2_1_train_i2i copy 3.py"
/home/recklexx/miniconda3/envs/pytorch-gpu/bin/python "/mnt/e/qiqilu/Project/2024 Foundation model/code/2_1_train_i2i copy 4.py"
/home/recklexx/miniconda3/envs/pytorch-gpu/bin/python "/mnt/e/qiqilu/Project/2024 Foundation model/code/2_1_train_i2i copy 5.py"
