"""
The checkpoints used in finetune evaluation stage.
"""

checkpoints_finetune = [
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-mt-sr-1",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-mt-sr-1\epoch_2000_iter_32000.pt",
    #     "biotisr-mt-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-mt-sr-2",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-mt-sr-2\epoch_2000_iter_32000.pt",
    #     "biotisr-mt-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-mt-sr-3",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-mt-sr-3\epoch_2000_iter_32000.pt",
    #     "biotisr-mt-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-mito-sr-1",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-mito-sr-1\epoch_2000_iter_70000.pt",
    #     "biotisr-mito-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-mito-sr-2",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-mito-sr-2\epoch_2000_iter_70000.pt",
    #     "biotisr-mito-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-mito-sr-3",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-mito-sr-3\epoch_2000_iter_70000.pt",
    #     "biotisr-mito-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-factin-nonlinear-sr-1",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-factin-nonlinear-sr-1\epoch_2000_iter_70000.pt",
    #     "biotisr-factin-nonlinear-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-factin-nonlinear-sr-2",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-factin-nonlinear-sr-2\epoch_2000_iter_70000.pt",
    #     "biotisr-factin-nonlinear-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-factin-nonlinear-sr-3",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-factin-nonlinear-sr-3\epoch_2000_iter_70000.pt",
    #     "biotisr-factin-nonlinear-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-1",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1\epoch_2000_iter_32000.pt",
    #     "biotisr-ccp-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-2",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2\epoch_2000_iter_32000.pt",
    #     "biotisr-ccp-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-3",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3\epoch_2000_iter_32000.pt",
    #     "biotisr-ccp-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-factin-sr-1",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-factin-sr-1\epoch_2000_iter_32000.pt",
    #     "biotisr-factin-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-factin-sr-2",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-factin-sr-2\epoch_2000_iter_32000.pt",
    #     "biotisr-factin-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-factin-sr-3",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-factin-sr-3\epoch_2000_iter_32000.pt",
    #     "biotisr-factin-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1\epoch_2000_iter_32000.pt",
    #     "biotisr-lysosome-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2\epoch_2000_iter_32000.pt",
    #     "biotisr-lysosome-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3\epoch_2000_iter_32000.pt",
    #     "biotisr-lysosome-sr-3",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-mt-sr-1",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-mt-sr-1\epoch_2000_iter_32000.pt",
    #     "biotisr-mt-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-mt-sr-2",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-mt-sr-2\epoch_2000_iter_32000.pt",
    #     "biotisr-mt-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-mt-sr-3",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-mt-sr-3\epoch_2000_iter_32000.pt",
    #     "biotisr-mt-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-mito-sr-1",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-mito-sr-1\epoch_2000_iter_70000.pt",
    #     "biotisr-mito-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-mito-sr-2",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-mito-sr-2\epoch_2000_iter_70000.pt",
    #     "biotisr-mito-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-mito-sr-3",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-mito-sr-3\epoch_2000_iter_70000.pt",
    #     "biotisr-mito-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-factin-nonlinear-sr-1",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-factin-nonlinear-sr-1\epoch_2000_iter_70000.pt",
    #     "biotisr-factin-nonlinear-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-factin-nonlinear-sr-2",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-factin-nonlinear-sr-2\epoch_2000_iter_70000.pt",
    #     "biotisr-factin-nonlinear-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-factin-nonlinear-sr-3",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-factin-nonlinear-sr-3\epoch_2000_iter_70000.pt",
    #     "biotisr-factin-nonlinear-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-1",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1\epoch_2000_iter_32000.pt",
    #     "biotisr-ccp-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-2",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2\epoch_2000_iter_32000.pt",
    #     "biotisr-ccp-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-3",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3\epoch_2000_iter_32000.pt",
    #     "biotisr-ccp-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-factin-sr-1",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-factin-sr-1\epoch_2000_iter_32000.pt",
    #     "biotisr-factin-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-factin-sr-2",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-factin-sr-2\epoch_2000_iter_32000.pt",
    #     "biotisr-factin-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-factin-sr-3",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-factin-sr-3\epoch_2000_iter_32000.pt",
    #     "biotisr-factin-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1\epoch_2000_iter_32000.pt",
    #     "biotisr-lysosome-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2\epoch_2000_iter_32000.pt",
    #     "biotisr-lysosome-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3\epoch_2000_iter_32000.pt",
    #     "biotisr-lysosome-sr-3",
    # ],
    # [
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-mt-sr-1",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-mt-sr-1\epoch_150_iter_36600.pt",
    #     "biotisr-mt-sr-1",
    # ],
    # [
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-mt-sr-2",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-mt-sr-2\epoch_150_iter_36600.pt",
    #     "biotisr-mt-sr-2",
    # ],
    # [
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-mt-sr-3",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-mt-sr-3\epoch_150_iter_36600.pt",
    #     "biotisr-mt-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-mito-sr-1",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-mito-sr-1\epoch_150_iter_82200.pt",
    #     "biotisr-mito-sr-1",
    # ],
    # [
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-mito-sr-2",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-mito-sr-2\epoch_150_iter_82200.pt",
    #     "biotisr-mito-sr-2",
    # ],
    # [
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-mito-sr-3",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-mito-sr-3\epoch_150_iter_82200.pt",
    #     "biotisr-mito-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-factin-nonlinear-sr-1",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-factin-nonlinear-sr-1\epoch_150_iter_82200.pt",
    #     "biotisr-factin-nonlinear-sr-1",
    # ],
    # [
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-factin-nonlinear-sr-2",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-factin-nonlinear-sr-2\epoch_150_iter_82200.pt",
    #     "biotisr-factin-nonlinear-sr-2",
    # ],
    # [
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-factin-nonlinear-sr-3",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-factin-nonlinear-sr-3\epoch_150_iter_82200.pt",
    #     "biotisr-factin-nonlinear-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-1",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1\epoch_150_iter_36600.pt",
    #     "biotisr-ccp-sr-1",
    # ],
    # [
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-2",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2\epoch_150_iter_36600.pt",
    #     "biotisr-ccp-sr-2",
    # ],
    # [
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-3",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3\epoch_150_iter_36600.pt",
    #     "biotisr-ccp-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-factin-sr-1",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-factin-sr-1\epoch_150_iter_36600.pt",
    #     "biotisr-factin-sr-1",
    # ],
    # [
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-factin-sr-2",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-factin-sr-2\epoch_150_iter_36600.pt",
    #     "biotisr-factin-sr-2",
    # ],
    # [
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-factin-sr-3",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-factin-sr-3\epoch_150_iter_36600.pt",
    #     "biotisr-factin-sr-3",
    # ],
    # [
    #     # ----------------------------------------------------------------------
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1\epoch_150_iter_36600.pt",
    #     "biotisr-lysosome-sr-1",
    # ],
    # [
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2\epoch_150_iter_36600.pt",
    #     "biotisr-lysosome-sr-2",
    # ],
    # [
    #     "unifmir",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3",
    #     "checkpoints\conditional\\finetune\\unifmir_mae_bs_1_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3\epoch_150_iter_36600.pt",
    #     "biotisr-lysosome-sr-3",
    # ],
    # --------------------------------------------------------------------------
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-1-2",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1-2\epoch_1000_iter_31000.pt",
    #     "biotisr-ccp-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-1-4",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1-4\epoch_500_iter_30500.pt",
    #     "biotisr-ccp-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-1-8",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1-8\epoch_250_iter_30500.pt",
    #     "biotisr-ccp-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-1-16",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1-16\epoch_131_iter_32000.pt",
    #     "biotisr-ccp-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-1-64",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1-64\epoch_32_iter_32000.pt",
    #     "biotisr-ccp-sr-1",
    # ],
    [
        "care",
        "-v2-newnorm-ft-inout-biotisr-ccp-sr-1-256",
        "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1-256\epoch_8_iter_32000.pt",
        "biotisr-ccp-sr-1",
    ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-2-2",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2-2\epoch_1000_iter_31000.pt",
    #     "biotisr-ccp-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-2-4",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2-4\epoch_500_iter_30500.pt",
    #     "biotisr-ccp-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-2-8",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2-8\epoch_250_iter_30500.pt",
    #     "biotisr-ccp-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-2-16",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2-16\epoch_131_iter_32000.pt",
    #     "biotisr-ccp-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-2-64",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2-64\epoch_32_iter_32000.pt",
    #     "biotisr-ccp-sr-2",
    # ],
    [
        "care",
        "-v2-newnorm-ft-inout-biotisr-ccp-sr-2-256",
        "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2-256\epoch_8_iter_32000.pt",
        "biotisr-ccp-sr-2",
    ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-3-2",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3-2\epoch_1000_iter_31000.pt",
    #     "biotisr-ccp-sr-3",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-3-4",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3-4\epoch_500_iter_30500.pt",
    #     "biotisr-ccp-sr-3",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-3-8",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3-8\epoch_250_iter_30500.pt",
    #     "biotisr-ccp-sr-3",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-3-16",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3-16\epoch_131_iter_32000.pt",
    #     "biotisr-ccp-sr-3",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-3-64",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3-64\epoch_32_iter_32000.pt",
    #     "biotisr-ccp-sr-3",
    # ],
    [
        "care",
        "-v2-newnorm-ft-inout-biotisr-ccp-sr-3-256",
        "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3-256\epoch_8_iter_32000.pt",
        "biotisr-ccp-sr-3",
    ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1-2",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1-2\epoch_1000_iter_31000.pt",
    #     "biotisr-lysosome-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1-4",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1-4\epoch_500_iter_30500.pt",
    #     "biotisr-lysosome-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1-8",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1-8\epoch_250_iter_30500.pt",
    #     "biotisr-lysosome-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1-16",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1-16\epoch_131_iter_32000.pt",
    #     "biotisr-lysosome-sr-1",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1-64",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1-64\epoch_32_iter_32000.pt",
    #     "biotisr-lysosome-sr-1",
    # ],
    [
        "care",
        "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1-256",
        "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1-256\epoch_8_iter_32000.pt",
        "biotisr-lysosome-sr-1",
    ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2-2",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2-2\epoch_1000_iter_31000.pt",
    #     "biotisr-lysosome-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2-4",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2-4\epoch_500_iter_30500.pt",
    #     "biotisr-lysosome-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2-8",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2-8\epoch_250_iter_30500.pt",
    #     "biotisr-lysosome-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2-16",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2-16\epoch_131_iter_32000.pt",
    #     "biotisr-lysosome-sr-2",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2-64",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2-64\epoch_32_iter_32000.pt",
    #     "biotisr-lysosome-sr-2",
    # ],
    [
        "care",
        "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2-256",
        "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2-256\epoch_8_iter_32000.pt",
        "biotisr-lysosome-sr-2",
    ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3-2",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3-2\epoch_1000_iter_31000.pt",
    #     "biotisr-lysosome-sr-3",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3-4",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3-4\epoch_500_iter_30500.pt",
    #     "biotisr-lysosome-sr-3",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3-8",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3-8\epoch_250_iter_30500.pt",
    #     "biotisr-lysosome-sr-3",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3-16",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3-16\epoch_131_iter_32000.pt",
    #     "biotisr-lysosome-sr-3",
    # ],
    # [
    #     "care",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3-64",
    #     "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3-64\epoch_32_iter_32000.pt",
    #     "biotisr-lysosome-sr-3",
    # ],
    [
        "care",
        "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3-256",
        "checkpoints\conditional\\finetune\care_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3-256\epoch_8_iter_32000.pt",
        "biotisr-lysosome-sr-3",
    ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-1-2",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1-2\epoch_1000_iter_31000.pt",
    #     "biotisr-ccp-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-1-4",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1-4\epoch_500_iter_30500.pt",
    #     "biotisr-ccp-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-1-8",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1-8\epoch_250_iter_30500.pt",
    #     "biotisr-ccp-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-1-16",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1-16\epoch_131_iter_32000.pt",
    #     "biotisr-ccp-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-1-64",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1-64\epoch_32_iter_32000.pt",
    #     "biotisr-ccp-sr-1",
    # ],
    [
        "dfcan",
        "-v2-newnorm-ft-inout-biotisr-ccp-sr-1-256",
        "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-1-256\epoch_8_iter_32000.pt",
        "biotisr-ccp-sr-1",
    ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-2-2",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2-2\epoch_1000_iter_31000.pt",
    #     "biotisr-ccp-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-2-4",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2-4\epoch_500_iter_30500.pt",
    #     "biotisr-ccp-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-2-8",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2-8\epoch_250_iter_30500.pt",
    #     "biotisr-ccp-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-2-16",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2-16\epoch_131_iter_32000.pt",
    #     "biotisr-ccp-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-2-64",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2-64\epoch_32_iter_32000.pt",
    #     "biotisr-ccp-sr-2",
    # ],
    [
        "dfcan",
        "-v2-newnorm-ft-inout-biotisr-ccp-sr-2-256",
        "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-2-256\epoch_8_iter_32000.pt",
        "biotisr-ccp-sr-2",
    ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-3-2",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3-2\epoch_1000_iter_31000.pt",
    #     "biotisr-ccp-sr-3",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-3-4",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3-4\epoch_500_iter_30500.pt",
    #     "biotisr-ccp-sr-3",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-3-8",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3-8\epoch_250_iter_30500.pt",
    #     "biotisr-ccp-sr-3",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-3-16",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3-16\epoch_131_iter_32000.pt",
    #     "biotisr-ccp-sr-3",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-ccp-sr-3-64",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3-64\epoch_32_iter_32000.pt",
    #     "biotisr-ccp-sr-3",
    # ],
    [
        "dfcan",
        "-v2-newnorm-ft-inout-biotisr-ccp-sr-3-256",
        "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-ccp-sr-3-256\epoch_8_iter_32000.pt",
        "biotisr-ccp-sr-3",
    ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1-2",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1-2\epoch_1000_iter_31000.pt",
    #     "biotisr-lysosome-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1-4",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1-4\epoch_500_iter_30500.pt",
    #     "biotisr-lysosome-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1-8",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1-8\epoch_250_iter_30500.pt",
    #     "biotisr-lysosome-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1-16",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1-16\epoch_131_iter_32000.pt",
    #     "biotisr-lysosome-sr-1",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1-64",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1-64\epoch_32_iter_32000.pt",
    #     "biotisr-lysosome-sr-1",
    # ],
    [
        "dfcan",
        "-v2-newnorm-ft-inout-biotisr-lysosome-sr-1-256",
        "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-1-256\epoch_8_iter_32000.pt",
        "biotisr-lysosome-sr-1",
    ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2-2",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2-2\epoch_1000_iter_31000.pt",
    #     "biotisr-lysosome-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2-4",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2-4\epoch_500_iter_30500.pt",
    #     "biotisr-lysosome-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2-8",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2-8\epoch_250_iter_30500.pt",
    #     "biotisr-lysosome-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2-16",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2-16\epoch_131_iter_32000.pt",
    #     "biotisr-lysosome-sr-2",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2-64",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2-64\epoch_32_iter_32000.pt",
    #     "biotisr-lysosome-sr-2",
    # ],
    [
        "dfcan",
        "-v2-newnorm-ft-inout-biotisr-lysosome-sr-2-256",
        "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-2-256\epoch_8_iter_32000.pt",
        "biotisr-lysosome-sr-2",
    ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3-2",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3-2\epoch_1000_iter_31000.pt",
    #     "biotisr-lysosome-sr-3",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3-4",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3-4\epoch_500_iter_30500.pt",
    #     "biotisr-lysosome-sr-3",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3-8",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3-8\epoch_250_iter_30500.pt",
    #     "biotisr-lysosome-sr-3",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3-16",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3-16\epoch_131_iter_32000.pt",
    #     "biotisr-lysosome-sr-3",
    # ],
    # [
    #     "dfcan",
    #     "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3-64",
    #     "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3-64\epoch_32_iter_32000.pt",
    #     "biotisr-lysosome-sr-3",
    # ],
    [
        "dfcan",
        "-v2-newnorm-ft-inout-biotisr-lysosome-sr-3-256",
        "checkpoints\conditional\\finetune\dfcan_mae_bs_16_lr_0.0001_newnorm-v2-ft-biotisr-lysosome-sr-3-256\epoch_8_iter_32000.pt",
        "biotisr-lysosome-sr-3",
    ],
]
